---
title: "Computation for Linguists"
subtitle: "Activity Day: Detective Gutenberg"
date: "October 13, 2025"
author: "Dr. Andrew M. Byrd"
format:
  revealjs:
    css: header_shrink.css
    theme: beige
    slide-number: true
    center: true
    toc: true
    toc-title: "Plan for the Day"
    toc-depth: 1
jupyter: python3
editor: source
---

# Review

# Activity: Detective Gutenberg

## Detective Gutenberg

**Goal:** discover what makes an author’s writing style distinctive using the Python tools you already know. 

  - If you don't remember how to do something, revisit past lectures.

**Today, you'll:**
  
1. Download two novels of your choice from Project Gutenberg
2. Load & clean the texts
3. Measure style and print up the results 

## Overview of Activity — Setup

- Create a new `qmd`, called `style_detective`. 
- Choose *any* **two novels** from [Project Gutenberg](https://www.gutenberg.org/), and download them using Python.
  - Use simple filenames (such as `alice.txt`)
- Manually edit your `txt` files, deleting any Project Gutenberg headers & footers (that aren't part of the book text itself)

## Overview of Activity — Read & Clean

- Read both files, and assign each to a clear variable name.
- Split the words up, cleaning whitespace and punctuation. Make all words lowercase as well.

## Overview of Activity — Explore the Data

- Next,  you will look for specific patterns.

1. How many words are there **in total**? How many **unique** words?
2. What is the **average word length**?
3. How many **adverbs** are there? Pick **three other affixes** to investigate.
4. How much **dialogue** is there?
5. What are the **most common words** (excluding “the,” “and,” “of”)?

## Overview of Activity — Share a Finding with Your Neighbors

Each of you will report at least one finding, such as:

> “Austen uses twice as many adverbs.”  
> “Brontë has longer words but fewer unique ones.”  
> “Dialogue = 12 % of *Jane Eyre*, 5 % of *Austen*.”

## If You Finish Early

- Add a third author (Dickens, Poe, Twain)  
- Feel free to add yourself as the third author!

## Go for it!

# Possible Discussions

## How to Tally Words?

```python
words = ["the", "the", "the", "boy", "boy", "dog", "dog", "cat"]

word_counts = {}

for wd in words:
    if wd in word_counts:              # Check to see if wd is there; if it is, increase value by 1
        word_counts[wd] = word_counts[wd] + 1
    else:                              # If not, create a new entry, set value at 1
        word_counts[wd] = 1
        
print(word_counts)
```
## A More Efficient Approach:

```python
words = ["the", "the", "the", "boy", "boy", "dog", "dog", "cat"]

word_counts = {}

for wd in words:
    word_counts[wd] = word_counts.get(wd, 0) + 1
        
print(word_counts)
```

- `.get(wd, 0)` checks if `wd` already has a count; which we then increase by 1

## Calculating Averages in Python

- What is an **average**?  How do we calculate it?
