---
title: "Computation for Linguists"
subtitle: "LaTeX, Day 3"
date: "September 3, 2025"
author: "Dr. Andrew M. Byrd"
format:
  revealjs:
    css: header_shrink.css
    theme: beige
    slide-number: true
    center: true
    toc: true
    toc-title: "Plan for the Day"
    toc-depth: 1
editor: visual
---

# Review

-   What did we talk about in Friday's class?

# LaTeX Packages

-   Allow you to use LaTeX in ways beyond its base features

-   "Declared" in the preamble with the command `\usepackage{packagename}`

-   ***Can*** conflict with each other!

    -   For this reason, the order in which you install the packages actually does matter.

        -   But, why?

## Loading a Package

-   Copy and paste the following in your "301-LaTeX-practice" project tex file.
-   The `lipsum` package generates placeholder text.

``` latex
\usepackage{lipsum}
\begin{document}

The \texttt{lipsum} package generates placeholder text.

One paragraph of filler:

\lipsum[1]

Two paragraphs of filler:

\lipsum[1-2]

\end{document}
```

## Loading a Package that's not in Overleaf

-   Let's try a different style for our "ipsum lorem" text. What happens when you load the following code?

``` latex
\documentclass{article}
\usepackage{duckuments}

\begin{document}
% Duck-themed filler (like blindtext):
\blindduck[1]     % 1 paragraph
\blindduck[1-2]   % paragraphs 1–2
\end{document}
```

## Loading a Package that's not in Overleaf

-   Download <a href="duckuments.sty" download>duckuments.sty</a>.
-   Upload this file into your project folder in Overleaf.
-   Now run the same code as before.
    -   What happens? What does this tell you about installing packages not automatically built into Overleaf?

## Packages: Options & Optional Arguments

-   We'll be loading up a useful list package: `enumitem`
-   Why not just use enumerate / itemize?
    -   `itemize` = black dots, fixed indentation, spacing
    -   `enumerate` = 1., 2., 3. ... only
    -   changing label style (a., i., A., etc.) or margins requires redefining macros, which isn't user-friendly
    -   vertical spacing is often too wide for handouts/homework.
-   TLDR - your examples and lists look more professional!

## Packages: Options & Optional Arguments

-   Let's load up `enumitem` to see how it works
-   Check out the customizations - can you modify the code to turn (c) into (d)?

``` latex
\documentclass{article}
\usepackage{enumitem} % no options

\begin{document}

% Default enumerate
\begin{enumerate}
  \item Alpha
  \item Beta
\end{enumerate}

% Customized enumerate (full label syntax)
\begin{enumerate}[label=(\alph*), start=3, nosep, leftmargin=*]
  \item starts at (c)
  \item then (d)
\end{enumerate}

\end{document}
```

## Packages: Options & Optional Arguments

-   `\begin{enumerate}[label=(\alph*), start=3, nosep, leftmargin=*]`
    -   We'd have to do this for all of our lists, if we wanted to modify them accordingly.
    -   Is there any way we can make this less clunky?
-   Yes! Invoke some options in your package declaration.

## Baseline: no package options

-   Let's add the option `shortlabels` to the package.

``` latex
\documentclass{article}
\usepackage[shortlabels]{enumitem}

\begin{document}

% Same effect, shorter to type:
\begin{enumerate}[(a)] % shorthand for label=(\alph*)
  \item alpha
  \item beta
\end{enumerate}

% Start at (c) with shorthand:
\begin{enumerate}[(a), start=3, nosep, leftmargin=*]
  \item starts at (c)
  \item then (d)
\end{enumerate}

% Other shorthands:
\begin{enumerate}[A.]   % -> A., B., C.
  \item First
  \item Second
\end{enumerate}

\begin{enumerate}[i.]   % -> i., ii., iii.
  \item One
  \item Two
\end{enumerate}
\end{document}
```

## Activity: Packages

-   Copy and paste this code into your "301-LaTeX-practice" project tex file.
    -   **Your task**: study the code, and identify precisely what the optional arguments and commands are doing.
    -   Feel free to discuss with neighbors!

``` latex
\documentclass[12pt]{article}

% enumitem with two options declared
\usepackage[shortlabels,inline]{enumitem}

% Setting defaults
\setlist[enumerate,1]{label=(\arabic*)}          % level 1: (1), (2), ...
\setlist[enumerate,2]{label=(\alph*)}            % level 2: (a), (b), ...
\setlist[itemize]{label=--}                      % itemize bullets are dashes

\begin{document}

\begin{itemize}
  \item Data: 100 speakers across 5 regions.
  \item Methods: Forced alignment \& manual checks.
  \item[\textbf{Note:}] Region 3 recordings have higher noise levels.
  \item Deliverable: 2–3 pages with plots.
\end{itemize}


\begin{enumerate}[start=3]             % (3), (4), ...
  \item Prepare audio
    \begin{enumerate}
      \item normalize
      \item trim silences
    \end{enumerate}
  \item Extract features
\end{enumerate}

% ... some text ...

\begin{enumerate}[resume]              % continues with (5)
  \item Train model
\end{enumerate}


In this study we (briefly) confirm 
\begin{enumerate*}[label=a., itemjoin={{; }}, itemjoin*={{; and }}]
  \item speaker balance
  \item region stratification
  \item license compliance
\end{enumerate*}
before proceeding.

\end{document}
```

# Funny Symbols: Non-English Scripts

-   We're linguists, so of course we work with lots of languages and funny scripts.
-   For instance, what do we do if we're citing French data?

``` latex
\'{a}, \`{a}, \^{a}, ç --> á, à, â, ç 
```

-   Or German?

``` latex
\"{a}, \ss --> ä, ß 
```

## Funny Symbols: IPA

-   We're going to use this idea with IPA
-   But we've of course got to load a package for this: `tipa`
-   Download the [TIPA manual](http://www.l.u-tokyo.ac.jp/~fkr/tipa/tipaman.pdf)
-   Let's load it up.

``` latex
\documentclass{article}
\usepackage{tipa}
```

## Funny Symbols: IPA

-   There are two ways you can use TIPA:

    1.  With individual characters:

    ``` latex
    \textprimstress h\textepsilon.\textltilde\t{o\textupsilon}
    ```

    2.  Within a `\textipa` environment

    ``` latex
    \textprimstress\textipa{hE.\textltilde\t{oU}}
    ```

-   To find the symbols, check out the [TIPA manual](http://www.l.u-tokyo.ac.jp/~fkr/tipa/tipaman.pdf)

## IPA Activity

-   In LaTeX, type out the following words using the TIPA package:

1.  computer

2.  sleepy

3.  "your first name"

## Funny Symbols: IPA & Other Scripts

-   But what about Japanese? It's easier than you think...
-   What happens when you run this code?

``` latex
\documentclass{article}
\usepackage{fontspec} % lets you pick system fonts

\setmainfont{Noto Serif CJK JP} % or another Japanese-capable font

\begin{document}

日本語の文を書いています。  % “I am writing a sentence in Japanese.”

\end{document}
```

## Funny Symbols: XeLaTeX

-   Click "Menu" --\> "Compiler" --\> "XeLaTeX"

``` latex
\documentclass{article}
\usepackage{fontspec} % lets you pick system fonts

\setmainfont{Noto Serif CJK JP} % or another Japanese-capable font

\begin{document}

日本語の文を書いています。  % “I am writing a sentence in Japanese.”

\end{document}
```

## Funny Symbols: XeLaTeX and IPA

-   Wait a minute... does this mean that we can use XeLaTeX with IPA symbols? See for yourself...

```latex

\documentclass{article}
\usepackage{fontspec}

\setmainfont{Doulos SIL} % a font with good IPA coverage

\begin{document}

ˈkʰæn ju ˈkɑpi ən ˈpeɪst ðɪs ˈsɛntəns ˈɪntu ˈoʊvɚˌlif

\end{document}
```

# Phonological Rules

\% %%%%%%%%%%%%%% % % Phonological Rules % %%%%%%%%%%%%%%

\begin{frame} \frametitle{Phonological Rules} \begin{exe} \ex \phonb{s}{z}{V}{V} (\textbackslash phonb) \ex \phonl{k}{c}{i} (\textbackslash phonl) \ex \phonr{t}{ts}{u} (\textbackslash phonr) \ex \phon{\textturnw}{w} (\textbackslash phon) \ex \phonb{\phonfeat{+stop \\ +consonant \\ +alveolar}}{[\textfishhookr]}{ \phonfeat{+vowel \\ +stressed}}{\phonfeat{+vowel \\ +stressed}} \end{exe} \end{frame}

## Phonology Activity

\% %%%%%%%%%%%%%% % % Phonological Rules % %%%%%%%%%%%%%%

## OT Tableaux

\% %%%%%%%%%%%%%% % % OT Tableaux : website % %%%%%%%%%%%%%%

\begin{frame} \frametitle{OT Tableaux} \centering {\huge http://meluhha.com/tableau/} \end{frame}

## OT Tableaux

\% %%%%%%%%%%%%%% % % OT Tableaux % %%%%%%%%%%%%%%

\begin{frame}  \centering \begin{center} \renewcommand*\arraystretch{1.2} \vspace{1.0cm} \scalebox{1}[1]{\begin{tabular}[t]{|rrl||c|c|c|} \cline{1-3}  \multicolumn{3}{|c||}{\textipa{/tup/}} & \hspace*{0.1cm} \begin{rotate}{45} NoCoda \end{rotate} \hspace*{0.2cm} & \hspace*{0.1cm} \begin{rotate}{45} Dep-V \end{rotate} \hspace*{0.2cm} & \hspace*{0.1cm} \begin{rotate}{45} Max-C \end{rotate} \hspace*{0.2cm} \\[0.5ex] \hline \hline a. & & \textipa{tup} & $\ast$! & \cellcolor{lightgray} & \cellcolor{lightgray} \\ \hline b. & \ding{43} & \textipa{tu} & & & \cellcolor{lightgray}$\ast$ \\ \hline c. & & \textipa{tupi} & & $\ast$! & \cellcolor{lightgray} \\ \hline \end{tabular}} \renewcommand*\arraystretch{1} \end{center} \end{frame}

# Activity Answers

-   What is your background in computing?

-   What would you like to get out of the course?

-   This is anonymous, so please answer truthfully!

-   This will help me better understand how to structure the class.
