---
title: "Computation for Linguists"
subtitle: "LaTeX, Day 1"
date: "September 5, 2025"
author: "Dr. Andrew M. Byrd"
format:
  revealjs:
    css: header_shrink.css
    theme: beige
    slide-number: true
    center: true
    toc: true
    toc-title: "Plan for the Day"
    toc-depth: 1
editor: visual
---

# Review

-   What is your background in computing?

-   What would you like to get out of the course?

-   This is anonymous, so please answer truthfully!

-   This will help me better understand how to structure the class.

# Beginning LaTeX

-   What is your background in computing?

-   What would you like to get out of the course?

-   This is anonymous, so please answer truthfully!

-   This will help me better understand how to structure the class.

\% %%%%%%%%%%%%%% % % Syntax Trees % %%%%%%%%%%%%%%

\centering \Tree [.CP [.C$'$ [.NP [.N$'$ [.N LaTeX ] ] ] [.VP [.V$'$ [.V is ] [.AP [.A$'$ [.A fun ] ] ] ] ] ] ]

\% %%%%%%%%%%%%%% % % Syntax Tree - More Complex % %%%%%%%%%%%%%%

\begin{frame} \centering {\small \Tree [.TP [.DP [.KP \qroof{The queen}.DP [.K’ [.K ’s ] ] ] [.D’ [.D $\emptyset_{+poss}$ ] \qroof{consort}.NP ] ] [.T’ [.T -ed ] [.VP \phantom{DP} [.V’ [.V notice ] \qroof{me}.DP ] ] ] ] } \end{frame}

\% %%%%%%%%%%%%%% % % Dependency Tree #1 % %%%%%%%%%%%%%%

\begin{frame} \centering \begin{tikzpicture}     \node (is-root) {is}         [sibling distance=3cm]         child { node {this} }         child {             node {tree}                 [sibling distance=1.5cm]                 child { node {an} }                 child { node {example} }                 child { node {.} }                 child[missing]         };     \path (is-root) +(0,-2.5\tikzleveldistance)         node {\textit{This is an example tree.}}; \end{tikzpicture} \end{frame}

\% %%%%%%%%%%%%%% % % Dependency Tree #2 % %%%%%%%%%%%%%%

\begin{frame} \centering \xytext{   \xybarnode{Peter} &~~~&   \xybarnode{and}     \xybarconnect(UL,U){-2}"_{\small conj}"     \xybarconnect(UR,U){2}"^{\small conj}"     &~~~&   \xybarnode{Mary} &~~~&   \xybarnode{bought}     \xybarconnect[8](UL,U){-4}"_{\small subj}"     \xybarconnect[13]{6}"^{\small punct}"     \xybarconnect[8](UR,U){4}"^{\small obj}"     &~~~&   \xybarnode{a} &~~~&   \xybarnode{car}     \xybarconnect(UL,U){-2}"_{\small det}"     &~~~&   \xybarnode{.} } \end{frame}

\% %%%%%%%%%%%%%% % % Dependency Tree #3 % %%%%%%%%%%%%%%

\begin{frame} \centering \begin{dependency}[theme = simple]    \begin{deptext}[column sep=1em]       A \& hearing \& is \& scheduled \& on \& the \& issue \& today \& . \\    \end{deptext}    \deproot{3}{ROOT}    \depedge{2}{1}{ATT}    \depedge[edge start x offset=-6pt]{2}{5}{ATT}    \depedge{3}{2}{SBJ}    \depedge{3}{9}{PU}    \depedge{3}{4}{VC}    \depedge{4}{8}{TMP}    \depedge{5}{7}{PC}    \depedge[arc angle=50]{7}{6}{ATT} \end{dependency} \end{frame}

\% %%%%%%%%%%%%%% % % Morphology % %%%%%%%%%%%%%%

\section{Morphology} \begin{frame}     \frametitle{Earlier Implosive System (Weiss 2009, K\"{u}mmel 2012)}         \begin{tabular}{|l||c|c|l||l|}             \hline             Manner &  Stop Type & & Manner & Stop Type\\             \hline             voiceless        & */t/         & $\rightarrow$     & voiceless &   */t/ \\             voiced implosive & */\texthtd/  & $\rightarrow$     & voiced  & */d/ \\             voiced           & */d/         & $\rightarrow$     & breathy & */d\super h/\\             \hline         \end{tabular} \end{frame}

%%%%%%%%%%%%%% % AVMs %%%%%%%%%%%%%%

\begin{frame} \frametitle{AVM.sty: Don't use \textbackslash\textbackslash, use \textbackslash cr (?)} \begin{avm} \[qstore & \{ \[det & \rm the \cr restpar & \[para & \@1 \cr restr & \{ \[reln & \rm poss \cr possessor & \@3 \cr possessed & \@1\]\}\ \bf union \q\{\@2\q\} \] \] \} \] \end{avm}  \end{frame}
\end{document}
